# Experiment Setup

title: "Experiment_2"
description: "Foo Bar"
regions:
  - name: "dining_room"
    min_x: 4.5
    max_x: 8.5
    min_y: -1.0
    max_y: 1.5
    min_z: 0
    max_z: 1.5
  - name: "kitchen"
    min_x: 6.5
    max_x: 9.0
    min_y: -5.7
    max_y: -2.0
    min_z: 0.0
    max_z: 1.5
  - name: "bedroom"
    min_x: -8.0
    max_x: -3.5
    min_y: -1.7
    max_y: 0.0
    min_z: 0.0
    max_z: 1.5
  - name: "living_room"
    min_x: -2.0
    max_x: 2.0
    min_y: -4.5
    max_y: -1.5
    min_z: 0.0
    max_z: 1.5
  - name: "family_room"
    min_x: -8.0
    max_x: -3.5
    min_y: -6.0
    max_y: -3.5
    min_z: 0.0
    max_z: 1.5
objects:
  - name: "cup"
    priors:
      - name: family_room
        weight: 0.5
      - name: bedroom
        weight: 0.5
      # - name: dining_room
      #   weight: 0.3
      # - name: family_room
      #   weight: 0.3
  - name: "spoon"
    priors:
      - name: kitchen
        weight: 0.5
      - name: bedroom
        weight: 0.5
observations:
  # - name: "spoon"
  #   x: 7.0
  #   y: -5.0
  #   z: 0.0
  # - name: "cup"
  #   x: -5.0
  #   y: -5.0
  #   z: 0.0
  # - name: "spoon"
  #   x: -6.0
  #   y: -0.8
  #   z: 0.0
  # - name: "cup"
  #   x: -3.5
  #   y: -0.8
  #   z: 0.0
frames:
  - "grasp_cup"
  - "grasp_spoon"
  - "stir_cup"
steps:
  - "Execute grasp_cup"

