# Experiment Setup

title: "Experiment_2"
description: "Spoon (kitchen, dining_room) Cup (kitchen, bedroom) Bowl (dining_room, living_room)"
regions:
  - name: "dining_room"
    min_x: 4.5
    max_x: 8.5
    min_y: 0.5
    max_y: 3.5
    min_z: 0
    max_z: 1.5
  - name: "kitchen"
    min_x: 6.5
    max_x: 9.0
    min_y: -5.0
    max_y: 0.0
    min_z: 0.0
    max_z: 1.5
  - name: "bedroom"
    min_x: -9.0
    max_x: -3.0
    min_y: -1.0
    max_y: 2.4
    min_z: 0
    max_z: 1.5
  - name: "living_room"
    min_x: -2.0
    max_x: 2.0
    min_y: -4.0
    max_y: 0.0
    min_z: 0.0
    max_z: 1.5
objects:
  - name: "spoon"
    priors:
      - name: "dining_room"
        weight: 0.5
      - name: "kitchen"
        weight: 0.5
  - name: "cup"
    priors:
      - name: kitchen
        weight: 0.5
      - name: bedroom
        weight: 0.5
  - name: "bowl" 
    priors:
      - name: "living_room"
        weight: 0.5  
      - name: "dining_room"
        weight: 0.5
frames:
  - "grasp_bowl"
  - "grasp_cup"
  - "grasp_spoon"
  - "pour_bowl"
  - "stir_bowl"
  - "stir_cup"
# observations:
#   - name: "spoon"
#     x: 6.5
#     y: 2
#     z: 0.7
#   - name: "cup"
#     x: 7
#     y: -3
#     z: 0.8
#   - name: "bowl"
#     x: 8
#     y: -1
#     z: 0.8
steps:
  - "Update Filters"

